version: '3'

networks:
  backend:
    driver: bridge

services:
  chineseocr:
    build: ./chineseocr
    restart: always
    command: sh /data/init.sh
    tty: true
    ports:
      - "8089:8089"
    volumes:
      - ./volumes:/data/chineseocr_lite/backend/logs
    networks:
      - backend